app/base/forms.py
# app/base/forms.py
"""
Base Forms
================
Forms built with WTForms for user authentication and content management.
"""
from flask_wtf import FlaskForm
from wtforms.fields import EmailField, TelField
from wtforms import validators, StringField, PasswordField, TextAreaField, \
    SubmitField, BooleanField
from wtforms_sqlalchemy.fields import QuerySelectMultipleField
from flask_wtf.file import FileField, FileAllowed
import sqlalchemy as sa
from ..extensions import db
from ..models import Tag, User

def tags():
    """Query factory for all available tags."""
    return Tag.query


# SUBMIT HELP FORM: send email for password or resend confirmation
class SubmitHelpForm(FlaskForm):
    email = EmailField('Email', validators=[validators.DataRequired(), validators.Email()])
    submit = SubmitField('Submit')
    
    
class ResetPasswordForm(FlaskForm):
    password = PasswordField('New Password', validators=[validators.DataRequired(), validators.Length(min=8)])
    password2 = PasswordField('Repeat Password', 
        validators=[validators.DataRequired(), validators.EqualTo('password')])
    submit = SubmitField('Reset Password')


class ChangePasswordForm(FlaskForm):
    current_password = PasswordField('Current Password', validators=[validators.DataRequired()])
    password = PasswordField('New Password', validators=[validators.DataRequired(), validators.Length(min=8)])
    password2 = PasswordField('Repeat New Password', 
        validators=[validators.DataRequired(), validators.EqualTo('password')])
    submit = SubmitField('Change Password')
    

class LoginForm(FlaskForm):
    """User login form."""
    email = StringField('Email', validators=[validators.DataRequired()])
    password = PasswordField('Password', validators=[validators.DataRequired()])
    remember_me = BooleanField('Remember Me')
    next = StringField('Next')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    """User registration form with custom validation."""
    username = StringField('Username', validators=[validators.DataRequired()])
    first_name = StringField('First Name', validators=[validators.DataRequired()])
    last_name = StringField('Last Name', validators=[validators.DataRequired()])
    email = EmailField('Email', validators=[validators.DataRequired(), validators.Email()])
    password = PasswordField('Password', validators=[validators.DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[
            validators.DataRequired(),
            validators.EqualTo('password', message='Passwords must match')
        ])
    submit = SubmitField('Register')

    def validate_username(self, username):
        """Check username uniqueness."""
        user = db.session.scalar(
            sa.select(User).where(User.username == username.data))
        if user is not None:
            raise validators.ValidationError('Please use a different username.')

    def validate_email(self, email):
        """Check email uniqueness."""
        user = db.session.scalar(
            sa.select(User).where(User.email == email.data))
        if user is not None:
            raise validators.ValidationError('Please use a different email address.')


class PostForm(FlaskForm):
    """Blog post creation/editing form."""
    image = FileField('Image', validators=[
        FileAllowed(['jpg', 'png'], 'Images only!')
    ])
    title = StringField('Title', [
        validators.DataRequired(),
        validators.Length(max=80)
    ])
    subtitle = StringField('Subtitle', [
        validators.DataRequired(),
        validators.Length(max=80)
    ])        
    body = TextAreaField('Content', validators=[validators.DataRequired()])
    tags = QuerySelectMultipleField('Tag', 
                                  query_factory=tags, 
                                  validators=[validators.DataRequired()])
    new_tag = StringField('New Tag')


class ContactForm(FlaskForm):
    """Contact form with custom name length validation."""
    def check_name_length(form, field):
        if len(field.data) < 4:
            raise validators.ValidationError('Name must have more than 3 characters')

    name = StringField('Your Name:', [validators.DataRequired(), check_name_length])
    email = StringField('Your e-mail address:', [
        validators.DataRequired(), 
        validators.Email('Please enter a valid email address')
    ])
    message = TextAreaField('Your message:', [validators.DataRequired()])
    submit = SubmitField('Send Message')


class SettingsForm(FlaskForm):
    """User settings form."""
    first_name = StringField('First name', [validators.DataRequired()])
    last_name = StringField('Last name', [validators.DataRequired()])
    about = TextAreaField('About me', [validators.Optional()])
    address = TextAreaField('Address', [validators.Optional()])
    phone = TelField('Phone', [validators.Optional()])
    image = FileField('Image', validators=[
        FileAllowed(['jpg', 'png'], 'Images only!')
    ])
    public_profile = BooleanField('Public profile')


class BuzzForm(FlaskForm):
    """Simple form for creating buzz objects."""
    title = StringField('Title', [validators.DataRequired()])
    body = TextAreaField('Body', [validators.DataRequired()])

app/base/__init__.py
from flask import Blueprint

base_blueprint = Blueprint('base', __name__)

from . import views, views_ajax, forms, decorators, views_login

app/base/views.py
"""
Base Routes
============
The basic routes at the core of the app, including: 
 - Homepage 
 - Settings page
 - Profile page
 - Blog pages
"""

# library imports
from flask import render_template, redirect, flash, url_for, session, request, current_app, send_from_directory, abort
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from flask_mail import Message
from slugify import slugify
from jinja2 import TemplateNotFound
import os, imghdr

# our objects
from . import base_blueprint as app # renamed to "app" so the blueprint layer fades to the background
from .. import db, mail, comms
from .forms import PostForm, ContactForm, SettingsForm, BuzzForm
from .decorators import roles_required
from ..models import Post, Tag, User, Buzz


@app.route('/')
@app.route('/index')
def index():
    """ Renders and returns the home page """
    data = {} 
    data['posts'] = Post.query.order_by(Post.published_at.desc()).all()
    return render_template('base/index.html', data=data)

@app.route('/settings', methods=('GET', 'POST'))
@app.route('/settings.html', methods=('GET', 'POST'))
@login_required
def settings():
    form = SettingsForm(obj=current_user)
    if form.validate_on_submit():
        # check out this cool new Python ternary operator: https://book.pythontips.com/en/latest/ternary_operators.html
        original_image = None if not current_user.image else current_user.image        
        form.populate_obj(current_user)  # this only works if the form property is the same name as the User property 
        current_user.image = original_image # avoid erasing any image properties just yet
        if form.image.has_file():
            image = request.files.get('image')
            filename = secure_filename(image.filename)
            try:
                # https://blog.miguelgrinberg.com/post/handling-file-uploads-with-flask
                path = f"{current_app.root_path}/static/uploads/{current_user.id}" # notice how I pass the user ID? That's cause we need the right folder
                if not os.path.exists(path):
                    os.mkdir(path)
                if filename != '':
                    file_ext = os.path.splitext(filename)[1]
                    if file_ext not in ['.jpg', '.png', '.gif'] or \
                            file_ext != validate_image(image.stream):
                        abort(400)
                image.save(os.path.join(f"{path}/", filename))
                current_user.image = str(filename)
                # delete the previous image if there was one
                try:                        
                    if original_image:
                        old_image_path = f"{current_app.root_path}/static/uploads/{current_user.id}/{original_image}"
                        os.remove(old_image_path)
                except Exception as e:
                    flash(f"Failed to delete previous image: {e}", 'danger')
            except Exception as e:
                flash(f"The image was not uploaded: {e}", 'danger')
        db.session.add(current_user)
        db.session.commit()
        flash("User updated", "success")
    return render_template('base/settings.html', form=form)

@app.route('/user/<int:user_id>')
@login_required
def profile(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    if current_user == user or user.public_profile:
        return render_template('base/profile.html', user=user)
    else:
        flash("UNAUTHORIZED ACCESS", "danger")
        return redirect(url_for('base.index'))
  
@app.route('/contact', methods=('GET', 'POST'))
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        # send email
        msg = Message("Message from your visitor" + form.name.data,
                          sender='noreply@flaskinni-dadiletta.c9users.io',
                          recipients=[app.config['ADMIN_EMAIL']])
        msg.body = """
        From: %s <%s>,
        %s
        """ % (form.name.data, form.email.data, form.message.data)
        with app.app_context():
            mail.send(msg)
        flash("Message sent", 'success')
        return redirect(url_for('index'))
    return render_template('base/contact.html', form=form)


@app.route('/admin', methods=('GET', 'POST'))
@roles_required('admin')
def admin():
    data = {}
    return render_template('base/admin.html', data=data)   

###################
####  POST
###################
@app.route('/blog/new', methods=('GET', 'POST'))
@login_required
@roles_required('admin')
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        image = request.files.get('image')
        filename = secure_filename(image.filename)
        try:
            # https://blog.miguelgrinberg.com/post/handling-file-uploads-with-flask
            path = f"{current_app.root_path}/static/uploads/blog" 
            if not os.path.exists(path):
                os.mkdir(path)
            if filename != '':
                file_ext = os.path.splitext(filename)[1]
                if file_ext not in ['.jpg', '.png', '.gif'] or \
                        file_ext != validate_image(image.stream):
                    abort(400)
            # TODO: check if file already exists with that name
            image.save(os.path.join(f"{path}/", filename))
            current_user.image = str(filename)
        except Exception as e:
            flash(f"The image was not uploaded: {e}", 'danger')
        # tags have been disabled
        if form.new_tag.data:
            new_tag = Tag(form.new_tag.data)
            db.session.add(new_tag)
            db.session.flush()
            tag = new_tag
        else:
            tag = form.tag.data
        title = form.title.data
        subtitle = form.subtitle.data
        body = form.body.data
        slug = slugify(title)
        post = Post(user_id=current_user.id, title=title, subtitle=subtitle, body=body, slug=slug, image=filename)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('base.read', slug=slug))
    return render_template('base/post.html', form=form, action="new")
    
@app.route('/article/<slug>')
def read(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    return render_template('base/article.html', post=post)
    
@app.route('/blog/edit/<int:post_id>', methods=('GET', 'POST'))
@roles_required('admin')
def edit_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    form = PostForm(obj=post)

    if form.validate_on_submit():
        original_image = None if not post.image else post.image    
        form.populate_obj(post)
        form.image = original_image # avoid accidentally overwriting image
        if form.image.has_file():
            image = request.files.get('image')
            filename = secure_filename(image.filename)
            try:
                # https://blog.miguelgrinberg.com/post/handling-file-uploads-with-flask
                path = f"{current_app.root_path}/static/uploads/blog"
                if not os.path.exists(path):
                    os.mkdir(path)
                if filename != '':
                    file_ext = os.path.splitext(filename)[1]
                    if file_ext not in ['.jpg', '.png', '.gif'] or \
                            file_ext != validate_image(image.stream):
                        abort(400)
                image.save(os.path.join(f"{path}/", filename))
                post.image = str(filename)
                # delete the previous image if there was one
                try:                        
                    if original_image:
                        old_image_path = f"{current_app.root_path}/static/uploads/blog/{original_image}"
                        os.remove(old_image_path)
                except Exception as e:
                    flash(f"Failed to delete previous image: {e}", 'danger')
            except Exception as e:
                flash(f"The image was not uploaded: {e}", 'danger')

        # TODO: restore tags
        if form.new_tag.data:
            new_tag = Tag(form.new_tag.data)
            db.session.add(new_tag)
            db.session.flush()
            post.tag = new_tag
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('base.read', slug=post.slug))
    return render_template('base/post.html', form=form, post=post, action="edit")

@app.route('/blog/delete/<int:post_id>')
@roles_required('admin')
def delete_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    post.live = False
    db.session.commit()
    flash("Article deleted", 'success')
    return redirect(url_for('base.index'))

#################
## HELPER METHODS
#################
@app.route('/view/<template>')
def route_template(template):
    """
    This is a pretty boss way to flexibly render any simple HTML file
    https://github.com/app-generator/boilerplate-code-flask-dashboard/blob/master/app/home/routes.py
    """
    try:
        if not template.endswith( '.html' ):
            template += '.html'

        if 'reset_instructions' in template:
            return render_template( f"base/email/{template}" )
        return render_template( f"base/{template}" )

    except TemplateNotFound:
        return render_template('base/404.html'), 404
    
    except Exception as e:
        current_app.logger.error(f'Failed to render template: {e}')
        return render_template('base/500.html'), 500

@app.route('/files/<int:user_id>/<path:filename>')
def uploaded_files(user_id, filename):
    """Function to serve up files"""
    path = current_app.config['UPLOADED_IMAGES_DEST'] + f"/{user_id}" # USER-BASED FOLDER SYSTEM so we can delete contents based on user
    return send_from_directory(path, filename)

def validate_image(stream):
    """ Checks image validity using Python's imghdr """
    # https://blog.miguelgrinberg.com/post/handling-file-uploads-with-flask
    header = stream.read(512)

app/templates/base/article.html
{% extends "base.html" %}

{% set title = post.title %}

{% block content %}

<div class="container-fluid">
  {% from "base/_helpers.html" import header_with_image, header %}
  {% if post and post.image %}
  {{ header_with_image(post.title, "postheader", post.img) }}
  {% else %}
  {{ header(post.title, "postheader") }}
  {% endif %}
  <div class="container">
      <div class="row justify-content-md-center">
          <div class="col-md-10">
            {% if current_user.has_role('admin') %}
              <a href="{{ url_for('base.edit_post', post_id=post.id) }}">Edit</a> -
              <a href="{{ url_for('base.delete_post', post_id=post.id) }}">Delete</a>
            {% endif %}
            <hr />
            <div class="text-muted">Posted by <a href="#">{{ post.user }}</a> on {{ post.pubdate }}.
            </div>
          </div>
      </div>
    <div class="row justify-content-md-center">
      <div class="col-md-10">
      <p>{{ post.body|safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/base/blank_page.html
{#####################################}
{############## SETTINGS #############}
{#####################################}
{% extends "base.html" %} 
{% block linkitem %}blankpage-link{% endblock %} {# hands off a variable to the script that activates the nav menu link items #}
{% block body_classes %}{% endblock %} {# place to insert options to change body layout #}
{% set title = "Blank Page" %} 
{% set meta_description = "This is my page's search engine description." %} 


{#####################################}
{################ BODY ###############}
{#####################################}
{% block content %}
  <!-- Begin Page Content -->
  <div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Blank Page</h1>
    </div>
  </div>
  <div class="container">
    {# - main content row - #}
    <div class="row">
    </div>
  </div>
{% endblock %}


{#####################################}
{################ TAIL ###############}
{#####################################}
{% block tail %}
<script>
  $( document ).ready(function() {
    console.log( "Template-specific script activated" );
  });
</script>
{% endblock %}


{#####################################}
{############## MODALS ###############}
{#####################################}
{% block modals %}
{% endblock %}

app/templates/base/contact.html
{% extends "base.html" %} 

{% block title %}Contact{% endblock %} 

{% block content %}
<section>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-6">   
               <form method="POST" action="{{ url_for('contact')}}">
                  {{ form.hidden_tag() }}
                  {{ render_field(form.name, class='form-control') }}
                  {{ render_field(form.email, class='form-control') }}
                  {{ render_field(form.message, class='form-control', rows=10) }}
                  {{ render_field_clean(form.submit, class='btn btn-default') }}
                </form>
            </div>
        </div>
    </div>
</section>                
{% endblock %}

app/templates/base/index.html
{% extends "base.html" %} 

{#- PAGE SETTINGS -#}
{% block linkitem %}homepage-link{% endblock %}
{% set title = "Home" %} 

{#- CONTENT -#}
{% block content %}

  {#- FULL-HEIGHT HERO -#}
  <div id="hero" class="full-height bg-gradient-secondary d-flex align-items-center">
    <img src="{{ url_for('static', filename='img/Flaskinni.png') }}"/>
  </div>

  <!-- Begin Page Content -->
  <div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Build with Flaskinni</h1>
      <a target="_blank" href="https://github.com/dadiletta/flaskinni" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> GitHub Repo</a>
    </div>
    {% if data['posts'] and data['posts']|length > 0 %}
        <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Blog</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
      
      {% for post in data['posts'] %}
        <div class="col-lg-6">

          <!-- Dropdown Card Example -->
          <div class="card shadow mb-4">
            {% if post.img %}
              <img class="card-img-top" src="{{ post.img }}" alt="{{ post.title }}">
            {% endif %}
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <h6 class="m-0 font-weight-bold text-primary">{{ post.title }}</h6>
              {% if current_user.has_role('admin') %}
              <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" x-placement="bottom-end" style="position: absolute; transform: translate3d(-156px, 18px, 0px); top: 0px; left: 0px; will-change: transform;">
                  <div class="dropdown-header">Admin Functions:</div>
                  <a class="dropdown-item" href="">Edit post</a>
                  <a class="dropdown-item delete" href="">Delete post</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="" target="_blank">View in new tab</a>
                </div>
              </div>
              {% endif %}
            </div>
            <!-- Card Body -->
            <div class="card-body">
              {{ post.body|safe|truncate(200) }}
              <hr>
              <a href="{{ url_for('base.read', slug=post.slug) }}" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>

{% endblock %} 

app/templates/base/post.html
{% extends "base.html" %}

{% block linkitem %}blogpost-link{% endblock %}
{% block title %}Blog Post{% endblock %}


{% block content %}


<div class="container-fluid">
  
  {% from "base/_helpers.html" import header %}
    {% if action=="new" %}
      {{ header("New Blog Post", "blogheader") }}
    {% else %}
      {{ header("Edit Blog Post", "blogheader") }}
  {% endif %}
  
  <div class="container">
      <div class="row justify-content-md-center">
          <div class="col-md-10">
            {% from "shared/_macros.html" import render_field %}
            {% if action=="new" %}<form method="POST" action="{{ url_for('base.new_post')}}" enctype="multipart/form-data" role="form">{% else %}<form method="POST" action="{{ url_for('base.edit_post', post_id=post.id)}}" enctype="multipart/form-data" role="form">
              {% endif %}
              {{ form.hidden_tag() }}

              {% if post and post.image %}
              <img src="{{ post.img }}" height="80px" class="img-rounded">
              {% endif %}

              {{ render_field(form.image, class='form-control') }}
              {{ render_field(form.title, class='form-control', placeholder="Title") }}
              {{ render_field(form.subtitle, class='form-control', placeholder="Subtitle") }}
              {{ render_field(form.body, class='form-control summernote', rows=10) }}
              <div class="row">
                <div class="col-md-6">
                  {{ render_field(form.tags, class='form-control') }}
                </div>
                <div class="col-md-6">
                  {{ render_field(form.new_tag, class='form-control') }}
                </div>
              </div>
              

              {% if action=="new" %}<button type="submit" class="btn btn-primary">Post</button>{% else %}
              <button type="submit" class="btn btn-primary">Update</button>{% endif %}

            </form>
          </div>
      </div>
  </div>
</div>

{% endblock %}

app/templates/base/profile.html
{% extends "base.html" %} 

{% set title = "Profile" %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ user }}</h1>
  </div>
</div>

<div class="container">
  <!-- Content Row -->
  <div class="row">
    {# A column should be used around here #}
    {# use getbootstrap.com for better example cards #}
    <!-- Basic Card Example -->
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">Simple Profile Card</h6>
				</div>
				<div class="card-body">
					{{ user.first_name }}<br/>{{ user.email }}<br/>
          {{ user.last_name }}<br/>{{ user.img }}<br/>
          {{ user.phone }}<br/>
          {{ user.address }}<br/>
          {% if user.last_seen %}
            Last seen {{ moment(user.last_seen).fromNow() }}
          {% else %}
            User has not logged in yet
          {% endif %}
          <br/>
          {% if user == current_user %}
            this is you!
          {% endif %}
				</div>
			</div>
    
	</div>
</div>

{% endblock %}

app/templates/base/settings.html
{% extends "base.html" %} 

{% block linkitem %}settings-link{% endblock %}
{% block title %}Settings{% endblock %} 
{% from 'shared/_macros.html' import render_field_with_errors, render_switch %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Settings</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <form action="{{ url_for('base.settings') }}" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="row">
          <div class="col-6">
            {{ render_field_with_errors(form.first_name, class="form-control", placeholder="First name") }}
            {{ render_field_with_errors(form.last_name, class="form-control", placeholder="Last name") }}
            {{ render_field_with_errors(form.phone, class="form-control", placeholder="Phone") }}
            {{ render_field_with_errors(form.address, class="form-control", placeholder="Address", rows=2) }}
            {{ render_switch(form.public_profile, "Show profile publicly", class="custom-control-input") }}
          </div>
          <div class="col-6">
            {% if current_user.image %}
              <img src="{{ current_user.imgsrc }}" width="100%" style="border-radius: 10px; box-shadow:2px 2px 15px #00000050;"/> 
            {% endif %}
            {{ render_field_with_errors(form.image) }}
            
          </div>
          <div class="col-12"> {# this ought to be on its own row, but whatever... #}
            {{ render_field_with_errors(form.about, class="form-control", placeholder="About") }}
            <button type="SUBMIT" class="btn btn-primary btn-lg w-100">Update Settings</button>
          </div>
        </div> {# -- CLOSE ROW-- #}
      </form>  {# CLOSE MY FORM #}
    </div>
  </div>

</div> {# CLOSE MY CONTAINER #}

{% endblock %}

app/templates/base/superadmin.html
{% extends "base.html" %} 

{% block linkitem %}superadmin-link{% endblock %}
{% set title = "Super Admin" %} 

{% block modals %}
	{% include "shared/modals/buzz_form.html" %}
{% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
	<!-- Page Heading -->
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800">Super Admin</h1>
			<a target="_blank" href="{{ url_for('base.admin') }}" class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm">
				<i class="fas fa-rocket fa-sm text-white-50"></i>  Admin
			</a>
	</div>

  	{# ---BUZZ FEED--- #}
	<div class="card shadow mb-4">
		<div class="card-header">
			
			<ul class="nav nav-tabs card-header-tabs">
				<li class="nav-item">
					<h6 class="nav-link font-weight-bold disabled text-primary">Buzz Feed</h6>
				</li>
				<li class="nav-item">
					<a class="nav-link small text-secondary" data-toggle="modal" data-target="#buzzForm"><i class="fas fa-plus"></i></a>
				</li>
			</ul>
		</div>
		<div class="card-body" id="buzzfeed">
			<div class="row">
				<div class="col-md-12">
					<div class="list-group">
						{% for buzz in data['buzz'] %}
						<a href="{{ buzz.generate_link() }}" class="list-group-item list-group-item-action">
							<div class="d-flex w-100 justify-content-between">
								<h5 class="mb-1">{{ buzz.title }}</h5>
								<small>{{ moment(buzz.created_on).fromNow() }}</small>
							</div>
							<p class="mb-1">{{ buzz.body|safe }}</p>
							<small>{{ buzz.user if buzz.user_id else "No user" }}</small>
						</a>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>

  {# <!-- USER TABLE --> #}
	{#   DataTales Example  #}
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">User Tables</h6>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Email</th>
							<th>Registered</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Email</th>
							<th>Registered</th>
							<th>Actions</th>
						</tr>
					</tfoot>
					<tbody>
						{% for user in data['users'] %}
						<tr>
							<td>{{ user.first_name }}</td>
							<td>{{ user.last_name }}</td>
							<td>{{ user.email }}</td>
							<td>{{ user.when_registered }}</td>
							<td>
								<div class="dropdown no-arrow mb-4">
									<button class="btn btn-secondary dropdown-toggle" type="button" id="{{ user.id }}-user-action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Action
									</button>
									<div class="dropdown-menu" aria-labelledby="{{ user.id }}-user-action">
										<a href="" class="dropdown-item"><i class="icon-pencil"></i> Edit User</a>
										<a href=""  class="dropdown-item delete"><i class="icon-trash"></i> Delete User</a>
									</div>
								</div>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	
	<!-- /USER TABLE -->
	
</div>

{% endblock %}

{% block tail %}

  <!-- Chart plugins -->
  <script src="{{ url_for('static', filename='vendor/chart.js/Chart.min.js') }}"></script>

  <!-- Page level custom scripts -->
  <script src="{{ url_for('static', filename='js/demo/chart-area-demo.js') }}"></script>
  <script src="{{ url_for('static', filename='js/demo/chart-pie-demo.js') }}"></script>
  <script src="{{ url_for('static', filename='js/demo/chart-bar-demo.js') }}"></script>


  <!-- Data Table plugins -->
  <script src="{{ url_for('static', filename='vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

  <!-- Data Table custom scripts -->
  <script src="{{ url_for('static', filename='js/demo/datatables-demo.js') }}"></script>


{% endblock %}